[package]
name = "shimakaze-ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wry = { version = "0.30.0", features = [
  "linux-body",
  "devtools",
  "transparent",
] }
