<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\Shimakaze.Foundation\src\Shimakaze.Foundation.Windowing.GLFW\Shimakaze.Foundation.Windowing.GLFW.csproj" />
    <ProjectReference Include="..\..\lib\Shimakaze.Foundation\src\Shimakaze.Foundation.Windowing.Rendering.OpenGL\Shimakaze.Foundation.Windowing.Rendering.OpenGL.csproj" />
    <ProjectReference Include="..\..\lib\Shimakaze.Foundation\src\Shimakaze.Foundation.Windowing.Rendering.Vulkan\Shimakaze.Foundation.Windowing.Rendering.Vulkan.csproj" />
    <ProjectReference Include="..\..\lib\Shimakaze.Foundation\src\Shimakaze.Foundation.Windowing.SDL\Shimakaze.Foundation.Windowing.SDL.csproj" />
    <ProjectReference Include="..\..\src\Shimakaze.UI.Controls\Shimakaze.UI.Controls.csproj" />
  </ItemGroup>

</Project>
