<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageVersion Include="Silk.NET.Windowing.Common" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
  </ItemGroup>
</Project>