<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.269" />
    <PackageVersion Include="Polyfill" Version="9.18.0" />
    <PackageVersion Include="Silk.NET.Core" Version="2.23.0" />
    <PackageVersion Include="SkiaSharp" Version="3.119.2" />
    <PackageVersion Include="SkiaSharp.HarfBuzz" Version="3.119.2" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.119.2" />
  </ItemGroup>
</Project>