<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Shimakaze.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shimakaze.UI.Rendering\Shimakaze.UI.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.HarfBuzz" />
  </ItemGroup>

</Project>