<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Shimakaze.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.HarfBuzz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\Shimakaze.Foundation\src\Shimakaze.Foundation.Windowing.Rendering\Shimakaze.Foundation.Windowing.Rendering.csproj" />
  </ItemGroup>

</Project>
