<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input.Glfw" />
    <PackageReference Include="Silk.NET.Windowing.Glfw" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shimakaze.UI.Core\Shimakaze.UI.Core.csproj" />
    <ProjectReference Include="..\Shimakaze.UI.Input\Shimakaze.UI.Input.csproj" />
  </ItemGroup>

</Project>
