using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Shimakaze.UI.MVVM.SourceGenerator;


[Generator(LanguageNames.CSharp)]
public sealed class ObservablePropertyGenerator : IIncrementalGenerator
{
    private const string ObservablePropertyFullName = "global::Shimakaze.UI.ObservablePropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ObservablePropertyFullName[8..],
                    static (node, ctx) =>
                    {
                        // 不是属性
                        if (node is not PropertyDeclarationSyntax property)
                            return false;

                        // 不是 partial 属性
                        if (!property.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)))
                            return false;

                        // 不在类里
                        if (property.Parent is not TypeDeclarationSyntax parent)
                            return false;

                        // 是结构体 或 接口
                        if (parent is StructDeclarationSyntax or InterfaceDeclarationSyntax)
                            return false;

                        // 不是静态类
                        if (parent.Modifiers.Any(static m => m.IsKind(SyntaxKind.StaticKeyword)))
                            return false;

                        // 类不在命名空间里 （排除内部类 但可能有排除 global::Class 的副作用）
                        if (parent.Parent is not BaseNamespaceDeclarationSyntax)
                            return false;

                        // 类不是 partial 类
                        if (!parent.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)))
                            return false;

                        return true;
                    },
                    static (context, ctx) =>
                    {
                        var property = (IPropertySymbol)context.TargetSymbol;

                        var get = string.Empty;
                        var set = string.Empty;

                        if (property.GetMethod?.DeclaredAccessibility < property.DeclaredAccessibility)
                            get = property.GetMethod.DeclaredAccessibility.GetCode();

                        if (property.SetMethod?.DeclaredAccessibility < property.DeclaredAccessibility)
                            set = property.SetMethod.DeclaredAccessibility.GetCode();

                        return new
                        {
                            ContainingType = property.ContainingType,
                            Type = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            Accessibility = property.DeclaredAccessibility.GetCode(),
                            Name = property.Name,
                            GetAccessibility = get,
                            SetAccessibility = set,
                        };
                    })
                .Where(i => i is not null)
                .Collect(),
            static (context, data) =>
            {
                foreach (var properties in data.GroupBy(i => i.ContainingType, SymbolEqualityComparer.Default))
                {
                    var type = (INamedTypeSymbol)properties.Key!;

                    using StringWriter code = new();
                    code.WriteLine("// Generated by Shimakaze.UI.MVVM.SourceGenerator.ObservablePropertyGenerator");
                    code.WriteLine("//     ❤ from Shimakaze.UI");
                    code.WriteLine();
                    code.WriteLine("#nullable enable");
                    code.WriteLine();
                    code.WriteLine($"namespace {type.ContainingNamespace.ToDisplayString()};");
                    code.WriteLine();
                    code.WriteLine($"{type.DeclaredAccessibility.GetCode()} partial {(type.IsRecord ? "record" : "class")} {type.Name}");
                    code.NewLine = "\r\n    ";
                    code.WriteLine('{');

                    foreach (var property in properties)
                    {
                        code.WriteLine($"{property.Accessibility} partial {property.Type} {property.Name}");
                        code.NewLine = "\r\n        ";
                        code.WriteLine('{');
                        if (property.GetAccessibility is not null)
                            code.WriteLine($"{property.GetAccessibility} get => field;".TrimStart());

                        if (property.SetAccessibility is not null)
                            code.WriteLine($"{property.SetAccessibility} set => SetProperty(ref field, value);".TrimStart());

                        code.GetStringBuilder().Length -= 4;
                        code.NewLine = "\r\n    ";
                        code.WriteLine('}');
                    }
                    code.GetStringBuilder().Length -= 4;
                    code.NewLine = "\r\n";
                    code.WriteLine('}');

                    context.AddSource(
                        $"{type.ToDisplayString()}.g.cs",
                        code.ToString());
                }
            });
    }

}
file static class AccessibilityExtensions
{
    public static string GetCode(this Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.Internal => "internal",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => string.Empty,
    };
}
